# A fully connected layer in PyTorch
**Other names**: A linear layer, A dense layer (in Tensorflow or Keras)

In [1]:
import torch

In [2]:
# create a matrix 
X = torch.arange(50, dtype=torch.float).view(10, 5) 
X

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34.],
        [35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44.],
        [45., 46., 47., 48., 49.]])

In [3]:
fc_layer = torch.nn.Linear(in_features=5, out_features=3) # bias=True is default
fc_layer

Linear(in_features=5, out_features=3, bias=True)

In [4]:
fc_layer.weight

Parameter containing:
tensor([[ 0.1325, -0.2247,  0.1653, -0.1677,  0.2888],
        [-0.3017,  0.0852,  0.0861, -0.4444,  0.0958],
        [ 0.2309, -0.2778,  0.3433, -0.4222,  0.0495]], requires_grad=True)

In [5]:
fc_layer.bias

Parameter containing:
tensor([ 0.4059, -0.2701,  0.3123], requires_grad=True)

In [6]:
# A = XW.t() + b
A = fc_layer(X)
A

tensor([[  1.1639,  -0.9627,  -0.3476],
        [  2.1354,  -3.3575,  -0.7290],
        [  3.1068,  -5.7522,  -1.1105],
        [  4.0783,  -8.1470,  -1.4920],
        [  5.0498, -10.5417,  -1.8734],
        [  6.0212, -12.9365,  -2.2549],
        [  6.9927, -15.3312,  -2.6363],
        [  7.9642, -17.7260,  -3.0178],
        [  8.9356, -20.1207,  -3.3993],
        [  9.9071, -22.5155,  -3.7807]], grad_fn=<AddmmBackward>)

In [7]:
# .size() is equivalent to .shape in PyTorch
print('X dim:', X.size())
print('Weights dim:', fc_layer.weight.size())
print('Bias dim:', fc_layer.bias.size())
print('A dim:', A)

X dim: torch.Size([10, 5])
Weights dim: torch.Size([3, 5])
Bias dim: torch.Size([3])
A dim: tensor([[  1.1639,  -0.9627,  -0.3476],
        [  2.1354,  -3.3575,  -0.7290],
        [  3.1068,  -5.7522,  -1.1105],
        [  4.0783,  -8.1470,  -1.4920],
        [  5.0498, -10.5417,  -1.8734],
        [  6.0212, -12.9365,  -2.2549],
        [  6.9927, -15.3312,  -2.6363],
        [  7.9642, -17.7260,  -3.0178],
        [  8.9356, -20.1207,  -3.3993],
        [  9.9071, -22.5155,  -3.7807]], grad_fn=<AddmmBackward>)
